### ISSUE TITLE
Handle Metadata

### ISSUE THREAD

**Issue by matthewstrasiotto** [matthewstrasiotto/pipetree#2]
We've discussed the idea of checking some high level aggregates / stats for targets as they are built by the pipeline, and I've been giving thought to the best way to do so. 

I believe that for each separate workflow ( that is- a given extract version / dataset, with the filetree structure as follows:

```yaml
root:
  logs: [ cmq_worker_^array_index^.log ] # etc
  pipeline:
   - drake_console.log
   - build_logs.log
   - raw:
       [ alert.csv, note_data_1.csv ] # etc
   - partition:
       [ alert.csv, note_data_1.csv] # etc
   # etc
```

we can add an extra file within `root/pipeline`, called `metadata.yaml`.

`metadata.yaml` should have the following fields, using the bulk 2013-2014 extract dataset as an example:

```yaml
title: bulk_2013_2014
desc:
 | The preliminary bulk extract from 2013 to 2014 - there are 
 some problems with the raw data- including that for some of the patient fields, the columns would be mis-aligned, and somehow one of the headers had a line-break
log_path: ./logs/workflows/bulk_2013_2014
log_root: .Rprojectroot # idk about this field, maybe? 
# the idea of the log_root would be to explicitly assign a logging location to root the tree at
# The .Rprojectroot, or some similar keyword would refer to the return of here::here()
```

This metadata file can be read, and then the `log_path` value would determine the subdirectory where structured logging could be placed for that extract / workflow / dataset
